### ISSUE TITLE
able to move off-screen from the start position

### ISSUE THREAD

**Issue by Chris660** [susam/invaders#1]
Hi.  I know this is just a for fun project, but I noticed that if the very first thing you do after starting a new game is press "left", the player sprite is allowed to move off-screen.  I assume this is not intentional.  

Browser: FF 97.0

**Comment by susam** [comment]
This was indeed a bug. Thank you, @Chris660, for reporting this and thank you, @jonmccreery, for sending the pull request to fix this. I have merged the pull request. Closing this issue now.
